In [2]:
import pandas as pd
df = pd.read_csv(r'D:\Coding\ML Projects\price_prediction_project\Data\btcusd_1-min_data.csv')

In [3]:
df.head(100)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
0,2018-01-01 00:00:00.000000,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000,1.675545e+06,1572,63.227133,8.576108e+05,0
1,2018-01-01 00:15:00.000000,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000,1.321757e+06,1461,47.686389,6.422812e+05,0
2,2018-01-01 00:30:00.000000,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000,1.078825e+06,1000,43.710406,5.900347e+05,0
3,2018-01-01 00:45:00.000000,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000,1.917783e+06,1195,73.897993,1.000614e+06,0
4,2018-01-01 01:00:00.000000,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000,9.778198e+05,898,34.257652,4.618369e+05,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-01-01 23:45:00.000000,13427.48,13454.47,13365.00,13380.00,78.582175,2018-01-01 23:59:59.999000,1.053343e+06,1192,24.258829,3.251872e+05,0
96,2018-01-02 00:00:00.000000,13382.16,13539.54,13382.16,13490.42,91.126953,2018-01-02 00:14:59.999000,1.228446e+06,1179,41.877218,5.642722e+05,0
97,2018-01-02 00:15:00.000000,13480.01,13700.04,13467.22,13700.04,82.646188,2018-01-02 00:29:59.999000,1.122874e+06,1091,42.543428,5.783005e+05,0
98,2018-01-02 00:30:00.000000,13700.00,13850.00,13689.71,13715.00,189.063763,2018-01-02 00:44:59.999000,2.604254e+06,2393,114.898537,1.583104e+06,0
99,2018-01-02 00:45:00.000000,13715.00,13770.00,13672.89,13750.01,103.759210,2018-01-02 00:59:59.999000,1.425354e+06,1348,55.636416,7.638600e+05,0

In [4]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 287085 entries, 0 to 287084
Data columns (total 12 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Open time                     287084 non-null  str
 1   Open                          287085 non-null  float64
 2   High                          287085 non-null  float64
 3   Low                           287085 non-null  float64
 4   Close                         287085 non-null  float64
 5   Volume                        287085 non-null  float64
 6   Close time                    287084 non-null  str
 7   Quote asset volume            287085 non-null  float64
 8   Number of trades              287085 non-null  int64
 9   Taker buy base asset volume   287085 non-null  float64
 10  Taker buy quote asset volume  287085 non-null  float64
 11  Ignore                        287085 non-null  int64
dtypes: float64(8), int64(2), str(2)
memory usage: 26.3 MB
None

In [5]:
print(df.describe())

                Open           High            Low          Close  \
count  287085.000000  287085.000000  287085.000000  287085.000000
mean    38293.959183   38368.843020   38216.629488   38294.161368
std     32492.869743   32540.435751   32444.162695   32492.901446
min      3166.110000    3174.780000    3156.260000    3167.070000
25%      9564.350000    9583.010000    9540.000000    9564.300000
50%     28193.810000   28247.100000   28137.900000   28193.830000
75%     59553.640000   59683.230000   59430.010000   59553.650000
max    126011.180000  126199.630000  125648.010000  126011.180000

              Volume  Quote asset volume  Number of trades  \
count  287085.000000        2.870850e+05      2.870850e+05
mean      669.845396        1.923938e+07      2.126590e+04
std      1072.715836        2.886679e+07      3.014507e+04
min         0.000000        0.000000e+00      0.000000e+00
25%       185.944100        3.672218e+06      4.540000e+03
50%       343.918367        9.874961e+06      1.058400e+04
75%       689.116170        2.345415e+07      2.501100e+04
max     40371.405060        1.086850e+09      1.754730e+06

       Taker buy base asset volume  Taker buy quote asset volume    Ignore
count                287085.000000                  2.870850e+05  287085.0
mean                    332.575697                  9.495192e+06       0.0
std                     535.218414                  1.446831e+07       0.0
min                       0.000000                  0.000000e+00       0.0
25%                      90.696940                  1.772468e+06       0.0
50%                     171.284840                  4.710256e+06       0.0
75%                     343.062106                  1.154712e+07       0.0
max                   19925.616600                  5.619115e+08       0.0

In [6]:
df['Open time'] = pd.to_datetime(df['Open time'])
df['Close time'] = pd.to_datetime(df['Close time'])

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 287085 entries, 0 to 287084
Data columns (total 12 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Open time                     287084 non-null  datetime64[us]
 1   Open                          287085 non-null  float64
 2   High                          287085 non-null  float64
 3   Low                           287085 non-null  float64
 4   Close                         287085 non-null  float64
 5   Volume                        287085 non-null  float64
 6   Close time                    287084 non-null  datetime64[us]
 7   Quote asset volume            287085 non-null  float64
 8   Number of trades              287085 non-null  int64
 9   Taker buy base asset volume   287085 non-null  float64
 10  Taker buy quote asset volume  287085 non-null  float64
 11  Ignore                        287085 non-null  int64
dtypes: datetime64[us](2), float64(8), int64(2)
memory usage: 26.3 MB
None

In [8]:
df['Opening Hours'] = df['Open time'].dt.hour
df['Opening day'] = df['Open time'].dt.day
df['Opening month'] = df['Open time'].dt.month

In [9]:
df.head(100)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,Opening Hours,Opening day,Opening month
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999,1.675545e+06,1572,63.227133,8.576108e+05,0,0.0,1.0,1.0
1,2018-01-01 00:15:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999,1.321757e+06,1461,47.686389,6.422812e+05,0,0.0,1.0,1.0
2,2018-01-01 00:30:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999,1.078825e+06,1000,43.710406,5.900347e+05,0,0.0,1.0,1.0
3,2018-01-01 00:45:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999,1.917783e+06,1195,73.897993,1.000614e+06,0,0.0,1.0,1.0
4,2018-01-01 01:00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999,9.778198e+05,898,34.257652,4.618369e+05,0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2018-01-01 23:45:00,13427.48,13454.47,13365.00,13380.00,78.582175,2018-01-01 23:59:59.999,1.053343e+06,1192,24.258829,3.251872e+05,0,23.0,1.0,1.0
96,2018-01-02 00:00:00,13382.16,13539.54,13382.16,13490.42,91.126953,2018-01-02 00:14:59.999,1.228446e+06,1179,41.877218,5.642722e+05,0,0.0,2.0,1.0
97,2018-01-02 00:15:00,13480.01,13700.04,13467.22,13700.04,82.646188,2018-01-02 00:29:59.999,1.122874e+06,1091,42.543428,5.783005e+05,0,0.0,2.0,1.0
98,2018-01-02 00:30:00,13700.00,13850.00,13689.71,13715.00,189.063763,2018-01-02 00:44:59.999,2.604254e+06,2393,114.898537,1.583104e+06,0,0.0,2.0,1.0
99,2018-01-02 00:45:00,13715.00,13770.00,13672.89,13750.01,103.759210,2018-01-02 00:59:59.999,1.425354e+06,1348,55.636416,7.638600e+05,0,0.0,2.0,1.0

In [10]:
print(df[['Open time', 'Close time']].head())
print(df.dtypes)

            Open time              Close time
0 2018-01-01 00:00:00 2018-01-01 00:14:59.999
1 2018-01-01 00:15:00 2018-01-01 00:29:59.999
2 2018-01-01 00:30:00 2018-01-01 00:44:59.999
3 2018-01-01 00:45:00 2018-01-01 00:59:59.999
4 2018-01-01 01:00:00 2018-01-01 01:14:59.999
Open time                       datetime64[us]
Open                                   float64
High                                   float64
Low                                    float64
Close                                  float64
Volume                                 float64
Close time                      datetime64[us]
Quote asset volume                     float64
Number of trades                         int64
Taker buy base asset volume            float64
Taker buy quote asset volume           float64
Ignore                                   int64
Opening Hours                          float64
Opening day                            float64
Opening month                          float64
dtype: object

In [11]:
df['Opening Hours'] = pd.to_datetime(df['Opening Hours'])
df['Opening day'] = pd.to_datetime(df['Opening day'])
df['Opening month'] = pd.to_datetime(df['Opening month'])

In [12]:
print(df.dtypes)

Open time                       datetime64[us]
Open                                   float64
High                                   float64
Low                                    float64
Close                                  float64
Volume                                 float64
Close time                      datetime64[us]
Quote asset volume                     float64
Number of trades                         int64
Taker buy base asset volume            float64
Taker buy quote asset volume           float64
Ignore                                   int64
Opening Hours                   datetime64[ns]
Opening day                     datetime64[ns]
Opening month                   datetime64[ns]
dtype: object

In [13]:
df['price_change'] = df['Close'] - df['Open']

In [14]:
df.head(5)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,Opening Hours,Opening day,Opening month,price_change
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999,1.675545e+06,1572,63.227133,8.576108e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-159.50
1,2018-01-01 00:15:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999,1.321757e+06,1461,47.686389,6.422812e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-12.63
2,2018-01-01 00:30:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999,1.078825e+06,1000,43.710406,5.900347e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-29.59
3,2018-01-01 00:45:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999,1.917783e+06,1195,73.897993,1.000614e+06,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,34.36
4,2018-01-01 01:00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999,9.778198e+05,898,34.257652,4.618369e+05,0,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-83.36

In [15]:
df['pct_change'] = (df['Close'] - df['Open']) / df['Open']
df.head(5)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,Opening Hours,Opening day,Opening month,price_change,pct_change
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999,1.675545e+06,1572,63.227133,8.576108e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-159.50,-0.011629
1,2018-01-01 00:15:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999,1.321757e+06,1461,47.686389,6.422812e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-12.63,-0.000933
2,2018-01-01 00:30:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999,1.078825e+06,1000,43.710406,5.900347e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-29.59,-0.002192
3,2018-01-01 00:45:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999,1.917783e+06,1195,73.897993,1.000614e+06,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,34.36,0.002546
4,2018-01-01 01:00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999,9.778198e+05,898,34.257652,4.618369e+05,0,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-83.36,-0.006162

In [16]:
df['ma_5'] = df['Close'].rolling(window=5).mean()
df['ma_10'] = df['Close'].rolling(window=10).mean()
df['volatility'] = df['Close'].rolling(window=5).std()

df.head(15)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,Opening Hours,Opening day,Opening month,price_change,pct_change,ma_5,ma_10,volatility
0,2018-01-01 00:00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999,1.675545e+06,1572,63.227133,8.576108e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-159.50,-0.011629,NaN,NaN,NaN
1,2018-01-01 00:15:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999,1.321757e+06,1461,47.686389,6.422812e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-12.63,-0.000933,NaN,NaN,NaN
2,2018-01-01 00:30:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999,1.078825e+06,1000,43.710406,5.900347e+05,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-29.59,-0.002192,NaN,NaN,NaN
3,2018-01-01 00:45:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999,1.917783e+06,1195,73.897993,1.000614e+06,0,1970-01-01 00:00:00.000000000,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,34.36,0.002546,NaN,NaN,NaN
4,2018-01-01 01:00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999,9.778198e+05,898,34.257652,4.618369e+05,0,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-83.36,-0.006162,13504.464,NaN,45.200900
5,2018-01-01 01:15:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999,1.189941e+06,939,45.135957,6.111437e+05,0,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,90.01,0.006682,13505.234,NaN,46.320421
6,2018-01-01 01:30:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999,1.004038e+06,1047,38.653471,5.219765e+05,0,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-119.98,-0.008848,13489.012,NaN,53.076276
7,2018-01-01 01:45:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999,1.982724e+06,1650,62.793323,8.354925e+05,0,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-236.95,-0.017630,13435.542,NaN,139.996136
8,2018-01-01 02:00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999,1.446924e+06,1528,40.703069,5.424858e+05,0,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,184.00,0.013936,13407.140,NaN,130.367138
9,2018-01-01 02:15:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999,1.265431e+06,1079,43.068838,5.726181e+05,0,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-162.00,-0.012101,13363.014,13433.739,149.950277
10,2018-01-01 02:30:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999,1.483295e+06,1074,53.247854,7.073543e+05,0,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,73.28,0.005531,13315.230,13410.232,101.831682
11,2018-01-01 02:45:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999,1.514541e+06,1206,55.218174,7.360464e+05,0,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-8.79,-0.000659,13293.264,13391.138,77.005996
12,2018-01-01 03:00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999,1.189070e+06,1070,35.514692,4.747012e+05,0,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,114.73,0.008607,13341.650,13388.596,82.002571
13,2018-01-01 03:15:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999,1.516663e+06,1415,43.355251,5.859573e+05,0,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,122.37,0.009105,13376.724,13391.932,129.814728
14,2018-01-01 03:30:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999,1.428926e+06,1051,32.728398,4.433612e+05,0,1970-01-01 00:00:00.000000003,1970-01-01 00:00:00.000000001,1970-01-01 00:00:00.000000001,-62.37,-0.004599,13431.724,13397.369,105.426817

In [17]:
df['future_close'] = df['Close'].shift(-7)

df['target'] = (df['future_close'] > df['Close']).astype(int)

df = df.dropna()

In [18]:

features = ['ma_5', 'ma_10', 'volatility', 'price_change']

X = df[features]
y = df['target']

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=5,
    random_state=42,
    eval_metric='logloss'
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [ ]:
y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.5284077054376981

In [22]:
y_pred

array([1, 0, 0, ..., 1, 0, 1], shape=(57414,))